### PR TITLE
PAXCONSTRUCT-142: upgrade to new master pom

### PR DESCRIPTION
**Pull request by bastijns-jeroen**

### CODE REVIEW

**Comment by bastijns-jeroen** [comment]
@ANierbeck or @jbonofre can you guys please have a look at it, so I can release paxconstruct?

**Comment by ANierbeck** [comment]
fine with me, as you have full rights now you don't need to work with pull-requests any-longer ... in case you break it, the ci server will tell you so keep an eye on it and fix it yourself ;)

**Comment by bastijns-jeroen** [comment]
Thx!

**Comment by bastijns-jeroen** [comment]
@ANierbeck any idea if the build starts on scm change? It hasn't run in the last 3 years (the last build was started manually) and I don't have the access with my account to login on Jenkins to start it. Can you run it?

**Comment by ANierbeck** [comment]
triggered, and should work now on change

**Comment by bastijns-jeroen** [comment]
thx!

**Comment by bastijns-jeroen** [comment]
@ANierbeck can you alter version 1.6 to 1.6.0 in jira and assign the remaining issues to 1.7.0?

**Comment by ANierbeck** [comment]
done

2016-01-11 13:24 GMT+01:00 bastijns-jeroen <notifications@github.com>:

> @ANierbeck <https://github.com/ANierbeck> can you alter version 1.6 to
> 1.6.0 in jira and assign the remaining issues to 1.7.0?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ops4j/org.ops4j.pax.construct/pull/6#issuecomment-170525622>
> .
>



-- 

Apache Member
Apache Karaf <http://karaf.apache.org/> Committer & PMC
OPS4J Pax Web <http://wiki.ops4j.org/display/paxweb/Pax+Web/> Committer &
Project Lead
blog <http://notizblog.nierbeck.de/>
Co-Author of Apache Karaf Cookbook <http://bit.ly/1ps9rkS>

Software Architect / Project Manager / Scrum Master

**Pull request merged**
